name: Run smoke tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      runtime:
        required: true
        type: string

jobs:
  smoke-test:
    name: smoke test on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup build env
        run: ./scripts/setup-linux.sh
        shell: bash
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: containerd-shim-${{ inputs.runtime }}-linux-musl
          path: dist
      - name: Unpack artifats
        shell: bash
        run: |
          mkdir -p dist/bin
          tar -xzf dist/containerd-shim-${{ inputs.runtime }}-linux-musl.tar.gz -C dist/bin
      - name: Download test image
        uses: actions/download-artifact@master
        with:
          name: test-img
          path: dist
      - name: run
        timeout-minutes: 5
        run: |
          ls -alh dist
          ls -alh dist/bin
          make load
          sudo cp -f dist/bin/* /usr/local/bin
          sudo ctr run --rm --runtime=io.containerd.${{ inputs.runtime }}.v1 ghcr.io/second-state/runwasi-demo:wasi-demo-app testwasm /wasi-demo-app.wasm echo 'hello'
